jobs:
  test:
    docker:
      - image: circleci/node:10-stretch
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo:4
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and test
          command: docker-compose -f docker-compose.test.yml up --build --exit-code-from sut
workflows:
  version: 2
  build_and_test:
    jobs:
      - test