jobs:
  test:
    docker:
      - image: circleci/node:10-stretch
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: mongo:4
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
  test-image:
    docker:
      - image: debian:stretch
    steps:
      - setup_remote_docker
      - run:
          docker pull t1bb4r/circleci-dockerhub-integration:latest-untested
      - run:
          docker run --rm -it -t t1bb4r/circleci-dockerhub-integration:latest-untested npm test
      - run:
          docker tag t1bb4r/circleci-dockerhub-integration:latest-untested t1bb4r/circleci-dockerhub-integration:latest
          docker push t1bb4r/circleci-dockerhub-integration:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - test